@echo off
::git status
::pause>nul
git pull origin main
git add .
git commit --allow-empty -m "Trigger GitHub Pages rebuild"
git push origin main
echo Searching...
timeout /t 5 >nul
echo Inspecting...
timeout /t 5 >nul
echo Parsing files...
timeout /t 5 >nul
echo Fixing as per the commitment...
timeout /t 5 >nul
echo Updating...
timeout /t 5 >nul
echo Checking...
timeout /t 5 >nul
echo Finally Deploying...
timeout /t 5 >nul
echo.
echo Changes made succesfully !